name: Label Syncing

on:
  workflow_dispatch:
  push:

jobs:
 # export-labels:
 #   name: Export Labels from Repo(s)
 #   runs-on: ubuntu-latest
 #   steps:
 #     - uses: EndBug/export-label-config@v1
 #       with:
 #         token: ${{ secrets.GITHUB_TOKEN }}
 #         raw-result: false
 #         add-aliases: true
      # By default every label entry will have an `aliases` property set to an empty array.
      # It's for EndBug/label-sync, if you don't want it you cans set this to `false`
  sync-labels:
    name: Sync Labels Between Repos
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/TheBoatyMcBoatFace/templates-and-tools/main/configs/labels.yml
